### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by miabonardi** [nonprofittechy/docassemble-ssioverpaymentwaiver#14]
`id: convert assets`
- Answered Yes, wrote "because", selected continue, and received `TypeError: string indices must be integers'

**Comment by nonprofittechy** [comment]
Resolved in https://github.com/nonprofittechy/docassemble-ssioverpaymentwaiver/commit/87df1edf5916359fc21c9e2eeeb7badf6f0f3cfd
