### ISSUE TITLE
Bug report: Page id: amount can pay

### ISSUE THREAD

**Issue by miabonardi** [nonprofittechy/docassemble-ssioverpaymentwaiver#20]
I received the following error and the interview will not let me continue. 
![Screen Shot 2020-12-05 at 1 04 12 PM](https://user-images.githubusercontent.com/65858862/101259958-61795e80-36fa-11eb-865d-8dae02756895.png)

**Comment by nonprofittechy** [comment]
This is what the screen should look like and does in Firefox:

![image](https://user-images.githubusercontent.com/7645641/101260843-b15b2400-3700-11eb-83af-02f793612884.png)

**Comment by nonprofittechy** [comment]
398b8eed69f2109366decc6e8bdccea6cd42849b
