### ISSUE TITLE
People should still do the waiver if they disagree, if they are time-barred from filing the appeal

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-ssioverpaymentwaiver#34]
time limit is 60 days from the time of mailing -- 5 days for mailing. so 65 days after the date on the notice.

Maybe we need to explain that they are too late to appeal and to do the over payment waiver anyway.

**Comment by nonprofittechy** [comment]
We can flesh out the exit screen a bit. E.g. link to https://www.lsc.gov/what-legal-aid/find-legal-aid

Don't kick them out if the letter was received more than 60 days ago. We can add another screening question to see when they were told about the overpayment.

**Comment by nonprofittechy** [comment]
Can you look to see if there is a downloadable appeal form for SSA overpayment?

**Comment by miabonardi** [comment]
Done.

**Comment by miabonardi** [comment]
Done.
