### ISSUE TITLE
Page id: income types

### ISSUE THREAD

**Issue by miabonardi** [nonprofittechy/docassemble-ssioverpaymentwaiver#35]
It might be beneficial for the user if "other support" and "other" were more clearly differentiated. 
- [x] use question language from PDF for "other support" and leave "other" as is

**Comment by nonprofittechy** [comment]
This will need to be adjusted in custom_income.py--just the display value should be changed

**Comment by nonprofittechy** [comment]
Update the list in custom_income.py inside modules to be a list of dictionaries, like what I started here:
```
def generate_income_list() -> list:
  return [
    {"SSDI": "SSDI"},
    {"SSR": "Social Security Retirement benefits"},
    {"SSI": "SSI"},
```

**Comment by nonprofittechy** [comment]
Eventually we want to synchronize this w/ how its asked on SSA-634, which is better. Will need to update the income types, the checklist screener (so people don't answer same thing 2x) and definition of `receives_support` in ssi_overpayment_waiver.yml

**Comment by miabonardi** [comment]
Done
