### ISSUE TITLE
Page id: ssa contact

### ISSUE THREAD

**Issue by miabonardi** [nonprofittechy/docassemble-ssioverpaymentwaiver#38]
When user selects "I don't know" on `Page id: overpayment reason`:
- On `Page id: ssa contact` the language is confusing: "Did you tell the Social Security Administration that I don’t know?" and "Did you talk to someone (by phone or in person) about the fact that I don’t know?"
- On `Page id: ssa contact followup` the language is confusing: "You said that you contacted the Social Security Administration to let them know that I don’t know." "After you reported that I don’t know, did the Social Security Administration change your benefits amount?"
To do:
 - [x] Add if statement to show a different sentence when user selects "I don't know"
 - [x] change  `- I don't know` to `- I don't know: dont_know`
 - [x] do a similar change for both questions.
 The same problem happens when user selects "Something else"

**Comment by nonprofittechy** [comment]
You are right, would make more sense to make the "i don't know" text generic in both screens.

**Comment by nonprofittechy** [comment]
```
- label: |
    % if overpayment_reason == "dont_know":
    "Did you tell Social Security about the change or event that made you overpaid?"
    % else: 
    "Did you tell the Social Security Administration that ${ overpayment_reason}"
    % endif
  field: informed_ssa
```

**Comment by miabonardi** [comment]
> - label: |
>     % if overpayment_reason == "dont_know":
>     "Did you tell Social Security about the change or event that made you overpaid?"
>     % else: 
>     "Did you tell the Social Security Administration that ${ overpayment_reason}"
>     % endif
>   field: informed_ssa

Tried to use this code to fix this issue but the first line of text is used every time regardless of the order. I have a feeling that it is reading `% if overpayment_reason` before getting to `== "dont_know":`.

**Comment by miabonardi** [comment]
Done
