### ISSUE TITLE
Add character limits and decide how to handle overflow

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-ssioverpaymentwaiver#41]

**Comment by miabonardi** [comment]
Year/Make/Model column

**Comment by miabonardi** [comment]
I cannot figure out how to limit the following (they should only have 21 characters available): 
      - "savings_explanation_1": ${assets.matches('savings').item(0).no_income_explanation if assets.matches('savings').item(0).value == 0 else ''}
      - "savings_explanation_2": ${assets.matches('savings').item(1).no_income_explanation if assets.matches('savings').item(1).value == 0 else ''}
