### ISSUE TITLE
id: business/property information

### ISSUE THREAD

**Issue by miabonardi** [nonprofittechy/docassemble-ssioverpaymentwaiver#79]
`id: business/property information` from financial_statement.yml is being asked but does not populate on the SSA-632 PDF. Should it be asked/populating? @nonprofittechy

**Comment by miabonardi** [comment]
`id: real estate review` also appears twice as a result if `real_estate.there_are_any` and `properties.there_are_any` are both selected. This seems like it could be a bug and that `properties.there_are_any` should not be in the SSA-632 interview.

**Comment by nonprofittechy** [comment]
it's on the new form version which i migrated to
